package com.eproseed.coe.assignments.model.adfbc.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 01 17:39:50 CEST 2016
// ---------------------------------------------------------------------
public interface Assignments extends ViewObject {
    void appendNewRow();
}

