package com.eproseed.coe.assignments.model.adfbc.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 06 17:09:45 CEST 2016
// ---------------------------------------------------------------------
public interface AssignmentsRow extends Row {
    void approve();
}

