// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.eproseed.coe.common.view.declcomp;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class CoeDashboardTileTag extends RichDeclarativeComponentTag {

  public CoeDashboardTileTag() {
  }

  public String getComponentType() {
    return "com.eproseed.coe.common.view.declcomp.CoeDashboardTileComponentType";
  }

  protected String getViewId() {
    return "/com/eproseed/coe/common/view/declcomp/CoeDashboardTile.jsf";
  }

  protected RichDeclarativeComponent createComponent() {
    return new CoeDashboardTileComponent();
  }

  public void setTileName(ValueExpression tileName) {
    this._tileName = tileName;
  }

  public void setTileId(ValueExpression tileId) {
    this._tileId = tileId;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_tileName != null)
      bean.setValueExpression(_TILENAME_KEY, _tileName);
    if (_tileId != null)
      bean.setValueExpression(_TILEID_KEY, _tileId);
  }

  public void release() {
    super.release();
    _tileName = null;
    _tileId = null;
  }

  private ValueExpression _tileName;
  private ValueExpression _tileId;

  private static final PropertyKey _TILENAME_KEY = PropertyKey.createPropertyKey("tileName");
  private static final PropertyKey _TILEID_KEY = PropertyKey.createPropertyKey("tileId");

}
