// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.eproseed.coe.common.view.declcomp;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class CoeDashboardTileComponent extends RichDeclarativeComponent {

  public CoeDashboardTileComponent() {
  }

  public String getTileName() {
    return (String) getAttributes().get("tileName");
  }

  public String getTileId() {
    return (String) getAttributes().get("tileId");
  }



}
