// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.eproseed.coe.common.view.declcomp;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class CoeLookupComponent extends RichDeclarativeComponent {

  public CoeLookupComponent() {
  }

  public Object getValue() {
    return (Object) getAttributes().get("value");
  }

  public Object getModel() {
    return (Object) getAttributes().get("model");
  }

  public String getDescrValue() {
    return (String) getAttributes().get("descrValue");
  }

  public String getPopupTitle() {
    return (String) getAttributes().get("popupTitle");
  }

  public String getLabel() {
    return (String) getAttributes().get("label");
  }

  public Object getColumns() {
    return (Object) getAttributes().get("columns");
  }

  public Boolean getAutoSubmit() {
    return (Boolean) getAttributes().get("autoSubmit");
  }

  public Boolean getImmediate() {
    return (Boolean) getAttributes().get("immediate");
  }

  public oracle.jbo.uicli.binding.JUCtrlAttrsBinding getValueBinding() {
    return (oracle.jbo.uicli.binding.JUCtrlAttrsBinding) getAttributes().get("valueBinding");
  }



}
