// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.eproseed.coe.common.view.declcomp;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class CoeTimePickerTag extends RichDeclarativeComponentTag {

  public CoeTimePickerTag() {
  }

  public String getComponentType() {
    return "com.eproseed.coe.common.view.declcomp.CoeTimePickerComponentType";
  }

  protected String getViewId() {
    return "/com/eproseed/coe/common/view/declcomp/CoeTimePicker.jsf";
  }

  protected RichDeclarativeComponent createComponent() {
    return new CoeTimePickerComponent();
  }

  public void setValueBinding(ValueExpression valueBinding) {
    this._valueBinding = valueBinding;
  }

  public void setLabel(ValueExpression label) {
    this._label = label;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_valueBinding != null)
      bean.setValueExpression(_VALUEBINDING_KEY, _valueBinding);
    if (_label != null)
      bean.setValueExpression(_LABEL_KEY, _label);
  }

  public void release() {
    super.release();
    _valueBinding = null;
    _label = null;
  }

  private ValueExpression _valueBinding;
  private ValueExpression _label;

  private static final PropertyKey _VALUEBINDING_KEY = PropertyKey.createPropertyKey("valueBinding");
  private static final PropertyKey _LABEL_KEY = PropertyKey.createPropertyKey("label");

}
