// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.eproseed.coe.common.view.declcomp;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class CoeTimePickerComponent extends RichDeclarativeComponent {

  public CoeTimePickerComponent() {
  }

  public oracle.jbo.uicli.binding.JUCtrlAttrsBinding getValueBinding() {
    return (oracle.jbo.uicli.binding.JUCtrlAttrsBinding) getAttributes().get("valueBinding");
  }

  public String getLabel() {
    return (String) getAttributes().get("label");
  }



}
