package com.eproseed.coe.departments.model.adfbc.views;

import com.eproseed.coe.common.model.adfbc.base.CoeViewObjectImpl;
import com.eproseed.coe.departments.model.adfbc.views.common.DepartmentsRO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 02 15:11:10 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsROImpl extends CoeViewObjectImpl implements DepartmentsRO {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsROImpl() {
    }


    /**
     * Returns the variable value for BDepartmentName.
     * @return variable value for BDepartmentName
     */
    public String getBDepartmentName() {
        return (String) ensureVariableManager().getVariableValue("BDepartmentName");
    }

    /**
     * Sets <code>value</code> for variable BDepartmentName.
     * @param value value to bind as BDepartmentName
     */
    public void setBDepartmentName(String value) {
        ensureVariableManager().setVariableValue("BDepartmentName", value);
    }
    
    public void searchDepartments(String departmentName) {
        setBDepartmentName(departmentName);
        executeQuery();
    }
}

