package com.eproseed.coe.departments.model.adfbc.views;

import com.eproseed.coe.common.model.adfbc.base.CoeViewRowImpl;

import java.math.BigDecimal;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 02 15:11:10 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsRORowImpl extends CoeViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DepartmentId,
        DepartmentName,
        ManagerId,
        LocationId,
        ManagerJobTitle,
        ManagerFirstName,
        ManagerLastName,
        PostalCode,
        City,
        EmployeesCnt,
        SalaryAvg;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int MANAGERJOBTITLE = AttributesEnum.ManagerJobTitle.index();
    public static final int MANAGERFIRSTNAME = AttributesEnum.ManagerFirstName.index();
    public static final int MANAGERLASTNAME = AttributesEnum.ManagerLastName.index();
    public static final int POSTALCODE = AttributesEnum.PostalCode.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int EMPLOYEESCNT = AttributesEnum.EmployeesCnt.index();
    public static final int SALARYAVG = AttributesEnum.SalaryAvg.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsRORowImpl() {
    }
}

