package com.eproseed.coe.departments.model.adfbc.views;

import com.eproseed.coe.common.model.adfbc.base.CoeViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 02 15:11:10 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsROImpl extends CoeViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsROImpl() {
    }
}

