package com.eproseed.coe.employees.model.adfbc.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 02 12:24:44 CEST 2016
// ---------------------------------------------------------------------
public interface EmployeesRecord extends ViewObject {
    void findEmployee(Long employeeId);
}

