package com.eproseed.coe.departments.model.adfbc.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 13 10:37:48 CEST 2016
// ---------------------------------------------------------------------
public interface DepartmentsRO extends ViewObject {
    void searchDepartments(String departmentName);
}

