package com.eproseed.coe.assignments.model.adfbc.views;

import com.eproseed.coe.assignments.model.adfbc.views.common.Assignments;
import com.eproseed.coe.common.model.adfbc.base.CoeViewObjectImpl;

import oracle.jbo.RowSetIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 01 17:27:46 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssignmentsImpl extends CoeViewObjectImpl implements Assignments {
    /**
     * This is the default constructor (do not remove).
     */
    public AssignmentsImpl() {
    }
    
    public void approveAll() {
        RowSetIterator rowsToBeApproved = null;
        try {
            rowsToBeApproved = createRowSetIterator("toBeApproved");
            while (rowsToBeApproved.hasNext()) {
                AssignmentsRowImpl row = (AssignmentsRowImpl) rowsToBeApproved.next();
                row.approve();
            }
            
        } finally {
            if (rowsToBeApproved!=null) {
                rowsToBeApproved.closeRowSetIterator();     
            }
        }
     
    }
}

