package com.eproseed.coe.employees.model.adfbc.views;

import com.eproseed.coe.common.model.adfbc.base.CoeViewObjectImpl;
import com.eproseed.coe.employees.model.adfbc.views.common.EmployeesRecord;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 02 12:23:05 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesRecordImpl extends CoeViewObjectImpl implements EmployeesRecord {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesRecordImpl() {
    }

    /**
     * Returns the variable value for BEmployeeId.
     * @return variable value for BEmployeeId
     */
    public Long getBEmployeeId() {
        return (Long) ensureVariableManager().getVariableValue("BEmployeeId");
    }

    /**
     * Sets <code>value</code> for variable BEmployeeId.
     * @param value value to bind as BEmployeeId
     */
    public void setBEmployeeId(Long value) {
        ensureVariableManager().setVariableValue("BEmployeeId", value);
    }
    
    public void findEmployee(Long employeeId) {
        setBEmployeeId(employeeId);
        executeQuery();
    }
}

